### ISSUE TITLE
Error in Node "Getting Started" example

### ISSUE THREAD

**Issue by chasestarr** [artsy/doppler#106]
Hi folks, 

While using the example code [here](https://developers.artsy.net/start) - the traverson module threw an error. It looks like the project broke out HAL support into a separate API:
```
throw new Error('JSON HAL adapter is not registered. From version ' +
      ^

Error: JSON HAL adapter is not registered. From version 1.0.0 on, Traverson has no longer built-in support for application/hal+json. HAL support was moved to a separate, optional plug-in. See https://github.com/basti1302/traverson-hal
```

Pulling in the separate module, and changing the import structure to below solved the issue. :tada: 

``` javascript
var traverson = require('traverson'),
	JsonHalAdapter = require('traverson-hal'),
	xappToken = [Token];

traverson.registerMediaType(JsonHalAdapter.mediaType, JsonHalAdapter);
var api = traverson.from('https://api.artsy.net/api').jsonHal();
```

**Comment by dblock** [comment]
Thanks! Would love it if you could PR a fix please?

**Comment by dblock** [comment]
Closed via https://github.com/artsy/doppler/pull/107. Thanks @chasestarr.
