### ISSUE TITLE
Missing comma after apiUrl variable declaration

### ISSUE THREAD

**Issue by dmatt** [artsy/doppler#127]
https://developers.artsy.net/start

Add a comma after `apiUrl`

https://github.com/artsy/doppler/blob/8a9e6be2ab4c726de51ff589d3ca1e52ef4a13cc/app/views/start/show.html.haml#L117

Results in an invalid declaration of the following variable `xappToken`

Screenshot:

https://www.dropbox.com/s/06huqj5tqyi1jsk/Screenshot%202017-09-11%2022.09.11.png?dl=0

**Comment by dblock** [comment]
Would you be so kind to PR a fix @dmatt ? Thanks!

**Comment by dmatt** [comment]
@dblock Sure! Here you go https://github.com/artsy/doppler/pull/128.
